# Generated by Django 5.0.6 on 2024-05-08 16:39

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=12, max_length=12, prefix='', primary_key=True, serialize=False)),
                ('post_content', models.CharField(max_length=255, verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
