# Generated by Django 5.0.6 on 2024-05-08 16:41

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=12, max_length=12, prefix='', primary_key=True, serialize=False),
        ),
    ]
